# Makefile for limit-cycles

lib.name = limit-cycles

common.sources = common.c lut.c
class.sources  = vdp~.c vdp_circle~.c lienard_even~.c brussel~.c
datafiles      = 

PDLIBBUILDER_DIR=.
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder
